### ISSUE TITLE
cycleVideo() in JS SDK gets "No video devices available" in iOS Safari

### ISSUE THREAD

**Issue by mrgrue** [opentok/opentok-react#119]
Using today's version of the JS SDK (2.17.2) as served from static.opentok.com, I get OT_NO_DEVICES_FOUND when trying to call publisher.cycleVideo(). I'm viewing using Safari on an iPhone running 13.4.1.

I've verified that the same thing happens when visiting https://opentok.github.io/opentok-web-samples/Publish-Devices/ with the same device. The only difference is that the error shows up as a popup saying "cycleVideo error No video devices available" instead of in the debug console.

**Comment by kaspesla** [comment]
Same issue on macOS Safari :(

**Comment by Medicmind** [comment]
I get the same issue but the behaviour is different on different iOS devices. Have issue on iphone 8, iphone se, iphone 11 but not iphone xr, iphone 6 or iphone 7

**Comment by enricop89** [comment]
Thanks for reporting. I believe it's an issue with the `2.17.2` version only. For now, the quick and dirty fix is using `2.17.1`.

**Comment by kaspesla** [comment]
Thanks! I will try and report back.
Ken

**Comment by kaspesla** [comment]
Does opentok post release notes somewhere where we could see changes in each update? (So we’d know when it’s fixed) 
Thanks,
Ken

**Comment by enricop89** [comment]
Sure! https://tokbox.com/developer/sdks/js/release-notes.html

**Comment by kaspesla** [comment]
Fixed in OpenTok.js 2.17.2

... The Publisher.cycleVideo() method sometimes returned an empty object. We have fixed this issue.

🤪🤦🏼‍♂️

**Comment by kaspesla** [comment]
Btw, Why on earth isn’t there just a setVideoDevice call like there is for Audio? Very strange. Cycling is a pretty odd experience on desktop.
Ken

**Comment by fictorial** [comment]
This is still happening. Mobile Safari 13.1 on iOS 13.4.1.

**Comment by Medicmind** [comment]
@fictorial  I'm still having the issue with 2.17.2 aswell.  2.17.1 works for me though.

**Comment by enricop89** [comment]
@fictorial if you want to load a specific version from the CDN, you can specify the version on the URL

https://static.opentok.com/v2.17.1/js/opentok.js

**Comment by enricop89** [comment]
Folks, the fixed version `2.17.3` is live: https://tokbox.com/developer/sdks/js/release-notes.html#fixedIssues 🚀 😃
